### ISSUE TITLE
Joomla Search will NOT pick up pages from SP-Page-Builder

### ISSUE THREAD

**Issue by fuzmic2** [JoomShaper/SP-Page-Builder#29]
We all know by now that Joomla Search (both smart or otherwise) will not search the content in the MySQL table.  From what i can see Joomla will only search Content, etc.  Thus a Search Plugin is required eg JSN page builder come with it.

Have any of you great guys create such .xml & .php that can be installed as a zip into Joomla.  Wishing!

**Comment by nayemmajhar** [comment]
Sorry. This feature available in pro version.

**Comment by fuzmic2** [comment]
Sure or not, I have seen paying guys complain, also acknowledge by sp

**Comment by syhussaini** [comment]
We design very large websites using SP Page Builder Pro Edition and the most sad part was it will simply not pickup the pages developed using Page Builder.

Tried to index them through Smart Search, but no page is getting indexed.
This is a major concern and should be addressed at the earliest.

Best Regards,
Syed H

**Comment by fuzmic2** [comment]
ZH, I trying to build plug-in but not able to complete yet so hoping sp
quickly mend this for their own good

**Comment by fuzmic2** [comment]
I just downloaded v 1.1.0, the search problem raised in this thread, i think, is still not resolved, there is no .php & .xml in the plugins\search\ folder.  Extension like JComments have this facility, so the search works.

Come on friends as sp, your product i like, please sort this out.

**Comment by nayemmajhar** [comment]
Do you use pro version of page builder? Only Joomla Search is available in Page Builder Pro.

**Comment by syhussaini** [comment]
More than anything, this should be taken up as a priority. Who would want a site that lacks in the search functionality. You have this awesome tool but without search function.

We need to have the Joomla Smart Search and Joomla Core Search function on the pages built by SP Page Builder.

 I am sure you will find and fix it.

Best Regards,
Syed H

**Comment by nayemmajhar** [comment]
Joomla core search is available in SP Page Builder pro. We will add smart
search feature soon in pro version.

Thanks

**Comment by syhussaini** [comment]
It does not work. I have tested it over Joomla 3.5.1 with SP Page Builder Prop v1.1.0
It picks up the titles that too rarely, no page content is ever picked in the search.

**Comment by nayemmajhar** [comment]
It always pick up page title not content because page builder content is
not like Joomla article content. Large amount HTML based content.

Do you have any idea about this how can be represented the content?

**Comment by syhussaini** [comment]
Then this should be clearly mentioned on the page as a downside of the page builder so that the developers who are using this tool do not build large sites using this tool resulting in a site with poor search. 

We cannot tell the users of the site to only type the words in the title, nor can we put the whole of the content in the title which makes it really weak. 

There has to be a fix. This is pushing several developers or buyers of this product go away from it. (See the forums of SP where lots of threads are only for this issue with no fix so far).

Even the page titles are not picked up properly. I have a site where there are around 9 pages with "OCM" in the title. But in the results it only shows 5.

Please do something about it.

**Comment by nayemmajhar** [comment]
I will check this issue

**Comment by farrukhali** [comment]
Still, no solution found anywhere for search indexing issue.

**Comment by pepperstreet** [comment]
# Tip & Workaround 
## How to get PageBuilder in Smart Search results 

PageBuilder v**2** works **inside** regular Joomla articles! 
Just use the Joomla core content and categories to build and structure your content. 
Edit Joomla article and use PageBuilder to layout content or load your existing separate pages.
Only limitation and extra step: You have to fill in the J! article text with important content.  
It will serve as a teaser or summary for your index. Otherwise you search titles only. 
Create Search filters to your liking. 

Bingo! Use smart search module or MenuItem to get PageBuilder pages in your results ;)    

### Side-Effect & benefit: 
You can even list and teaser multiple PB pages in Category MenuItems! 
 
### Headsup!
If you save and leave the article edit screen, always remember to set the PB page editor!!!  

---

### Screenshots

**Comment by mploscar** [comment]
This is really frustrating that I can't search content within the built SP pages. I've searched even their forums and this issue is around for a long time now. Please fix this!
